### ISSUE TITLE
Case Summary - add logo and sidebar menu mock up

### ISSUE THREAD

**Issue by jkoren** [codeforboston/home-energy-analysis-tool#120]
Mentioned by Steve in call on 12/5/23.  Addition to mock up delivered in [PR 103](https://github.com/codeforboston/home-energy-analysis-tool/pull/103)

Design in ready for dev [Figma page](https://www.figma.com/file/qaxsZ6TW7gjQdUGjuPypZ5/heat-tool-design-%2F%5Bnew-one%5D?type=design&node-id=2105%3A12877&mode=design&t=1hAL47vTKTWXAHco-1)

Also, match mockup UI to this Figma.

![Image](https://github.com/codeforboston/home-energy-analysis-tool/assets/67333843/a14a4015-5cf3-441d-b370-5ad05fd269e7)

**Comment by baipai** [comment]
@jkoren Hi, during our design meeting, we had a conversation and realized the need to review it before implementation. So, please don't do it now.

**Comment by plocket** [comment]
Closing this as on hold for now as it may be confusing to keep it open. I couldn't add a column to the Project, but it might be useful to add an "on hold" column for these issues.

I'm not sure how to "close" this properly as it's not resolved, but it's also still planned, so for now I'm marking that it's not planned. I figure that's the most appropriate since the design depicted in the instructions above isn't the one we will implement.

**Comment by plocket** [comment]
Also, this sidebar should be for the whole form route, not just for the case summary route.
