### ISSUE TITLE
Scan Excel Sheet Cells and Determine the necessary Python Function

### ISSUE THREAD

**Issue by Leopardfoot** [codeforboston/home-energy-analysis-tool#3]
Look through the HEAT Rules Engine Excel sheet and determine Python functions for the cells.

**Comment by mciethan** [comment]
Anyone who is working on this task: feel free to message me on Slack or take a look at the notes I've been writing up in our shared drive, so that we can sync up our work. Once we have reasonably good idea of the functions we need based on what's in the spreadsheet, we can write up a specific list of methods / functionalities with desired inputs and outputs and use that list to populate new issues / project guideposts for the Rules Engine side of things.

**Comment by mciethan** [comment]
https://docs.google.com/document/d/1PJU_LBMxDQef0xJiuMxaD4PlO8woMvdh1xVI4ChluGw/edit?usp=sharing

**Comment by mciethan** [comment]
At this point, I think the above notes are sufficient for starting Python development. Unless there is anything else, I think this issue can be closed.
